spring.application.name=bancoxyz-ms-clientes
server.port=8090

spring.datasource.url=jdbc:h2:mem:bancoxyz_clientes;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

logging.level.cl.duoc.bancoxyz.ms=DEBUG
