spring.application.name=rutaexpress-bff-movil
server.port=8092

ms-clientes.base-url=http://localhost:8090

canal.nombre=MOVIL
canal.api-key=movil-2026-key

logging.level.cl.duoc.rutaexpress.bff=DEBUG
