spring.application.name=bancoxyz-bff-web
server.port=8091

ms-clientes.base-url=http://localhost:8090
ms-tarjetas.base-url=http://localhost:8095

canal.nombre=WEB
canal.api-key=web-2026-key

logging.level.cl.duoc.bancoxyz.bff=DEBUG
