spring.application.name=bancoxyz-bff-movil
server.port=8092

ms-clientes.base-url=http://localhost:8090
ms-tarjetas.base-url=http://localhost:8095

canal.nombre=MOVIL
canal.api-key=movil-2026-key

logging.level.cl.duoc.bancoxyz.bff=DEBUG
