spring.application.name=rutaexpress-bff-cajero
server.port=8093

ms-clientes.base-url=http://localhost:8090

canal.nombre=CAJERO
canal.api-key=cajero-2026-key

logging.level.cl.duoc.rutaexpress.bff=DEBUG
